# Generated by Django 4.1.6 on 2023-02-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('P', 'Patient'), ('D', 'Doctor')], default='P', max_length=2, verbose_name='Type(P-Patient, D-Doctor)'),
        ),
    ]
