# Generated by Django 4.1.6 on 2023-02-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default=None, upload_to='Users/', verbose_name='Image'),
        ),
    ]
