# Generated by Django 4.1.6 on 2023-02-14 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_alter_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category name')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('image', models.ImageField(upload_to='Posts/', verbose_name='Image')),
                ('summary', models.CharField(max_length=255, verbose_name='Summary')),
                ('content', models.TextField(max_length=1000, verbose_name='Content')),
                ('drafted', models.BooleanField(default=False, verbose_name='Draft')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.categories', verbose_name='categories')),
                ('created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created user')),
            ],
        ),
    ]
