# Generated by Django 4.1.6 on 2023-02-14 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_categories_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Auto created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Auto created date'),
            preserve_default=False,
        ),
    ]
