# Generated by Django 4.1.6 on 2023-02-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_blog_date_categories_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Views'),
        ),
    ]
