# Generated by Django 4.1.6 on 2023-02-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_alter_blog_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Posts/', verbose_name='Image'),
        ),
    ]
